# Requires ttBld.exe version 1.2.0 or higher to process

Options:
    Project:     ttTIcpp      # project name
    Exe_type:    lib          # [window | console | lib | dll]
    Pch:         pch.h        # name of precompiled header file, or "none" if not using precompiled headers

    CFlags_cmn:  /std:c++17 -DUNICODE -D_UNICODE -DTIXML_USE_TICPP

    Optimize:    space        # [space | speed] optimization to use in release builds
    Warn:        4            # [1-4] warning level
    Crt_rel:     dll          # [static | dll] type of CRT to link to in release builds
    Crt_dbg:     dll          # [static | dll] type of CRT to link to in debug builds

    64Bit:       true         # [true | false] indicates if project can be built as a 64-bit target
    TargetDir64: lib64        # 64-bit target directory
    32Bit:       true         # [true | false] indicates if project can be built as a 32-bit target
    TargetDir32: lib32        # 32-bit target directory

Files:
    ticpp.cpp
    tinystr.cpp
    tinyxml.cpp
    tinyxmlerror.cpp
    tinyxmlparser.cpp
