# Requires ttBld.exe version 1.4.0 or higher to process

Options:
    Project:     ttTIcpp      # project name
    Exe_type:    lib          # [window | console | lib | dll]
    Pch:         pch.h        # name of precompiled header file, or "none" if not using precompiled headers

    IncDirs:     precomp      # additional directories for header files
    CFlags_cmn:  /std:c++17 -DUNICODE -D_UNICODE -DTIXML_USE_TICPP    # flags to pass to the compiler in all builds

    Optimize:    space        # [space | speed] optimization to use in release builds
    Warn:        4            # [1-4] warning level
    Crt_rel:     dll          # [static | dll] type of CRT to link to in release builds
    Crt_dbg:     dll          # [static | dll] type of CRT to link to in debug builds

    TargetDir:   lib          # target directory

Files:
    ticpp.cpp
    tinystr.cpp
    tinyxml.cpp
    tinyxmlerror.cpp
    tinyxmlparser.cpp
